const data = [
	{
		id: 1,
		name_german: "Dachs",
		name: "Badger",
		hint_1: "Bevorzugt dunkle und geschützte Orte.",
		hint_2: "Gräbt tiefe, weitläufige Höhlensysteme.",
		hint_3: "Besitzt ein auffälliges schwarz-weiß gestreiftes Gesicht.",
		trivia: "Badgers live in family groups called clans.",
		Paw: "Breite Pfote mit starken Krallen zum Graben.",
	},
	{
		id: 2,
		name_german: "Eichhörnchen",
		name: "Squirrel",
		hint_1: "Bewegt sich flink zwischen verschiedenen Ebenen.",
		hint_2: "Sammelt Nahrung und legt Vorräte für karge Zeiten an.",
		hint_3: "Hat einen langen, buschigen Schwanz zur Balance.",
		trivia: "Squirrels can rotate their ankles 180 degrees to climb down trees headfirst.",
		Paw: "Kleine Pfote mit scharfen Krallen für das Klettern.",
	},
	{
		id: 3,
		name_german: "Eule",
		name: "Owl",
		hint_1: "Bewegt sich lautlos durch die Dunkelheit.",
		hint_2: "Hat außergewöhnlich scharfe Sinne.",
		hint_3: "Kann den Kopf weit drehen und besitzt große, runde Augen.",
		trivia: "Owls have asymmetrical ears to help them pinpoint sounds.",
		Paw: "Starke Greifpfote mit scharfen Krallen.",
	},
	{
		id: 4,
		name_german: "Frosch",
		name: "Frog",
		hint_1: "Lebt an Orten, die feucht oder nass sind.",
		hint_2: "Hat eine glatte Haut, die oft bunt gefärbt ist.",
		hint_3: "Springt mit kräftigen Hinterbeinen und gibt laute Rufe von sich.",
		trivia: "Some frog species can freeze during winter and thaw in spring.",
		Paw: "Breite, schwimmfähige Pfoten mit Häuten zwischen den Zehen.",
	},
	{
		id: 5,
		name_german: "Fuchs",
		name: "Fox",
		hint_1: "Anpassungsfähig und in vielen Lebensräumen zu finden.",
		hint_2: "Bewegt sich oft leise und unauffällig.",
		hint_3: "Hat ein rötliches Fell und eine lange, buschige Rute.",
		trivia: "Foxes use the Earth's magnetic field to hunt.",
		Paw: "Schmale Pfote mit scharfen Krallen für geschickte Bewegungen.",
	},
	{
		id: 6,
		name_german: "Hase",
		name: "Hare",
		hint_1: "Lebt oft auf offenen Flächen und ist schnell verschwunden.",
		hint_2: "Hat auffallend lange Hinterbeine.",
		hint_3: "Kann mit hoher Geschwindigkeit weite Sprünge machen.",
		trivia: "Hares are born with fur and open eyes, unlike rabbits.",
		Paw: "Große, kräftige Pfote für schnelles Laufen.",
	},
	{
		id: 7,
		name_german: "Igel",
		name: "Hedgehog",
		hint_1: "Meistens nachts aktiv und tagsüber versteckt.",
		hint_2: "Kann sich bei Gefahr zusammenrollen.",
		hint_3: "Besitzt einen Körper voller kurzer Stacheln.",
		trivia: "Hedgehogs can hibernate during the cold months.",
		Paw: "Kleine Pfote mit kräftigen Zehen für das Graben.",
	},
	{
		id: 8,
		name_german: "Krähe",
		name: "Crow",
		hint_1: "Besonders intelligent und sehr anpassungsfähig.",
		hint_2: "Kann Werkzeuge nutzen und Rätsel lösen.",
		hint_3: "Hat glänzend schwarzes Gefieder und einen kräftigen Schnabel.",
		trivia: "Crows can recognize individual human faces.",
		Paw: "Kräftige Greifpfote mit scharfen Krallen.",
	},
	{
		id: 9,
		name_german: "Marder",
		name: "Marten",
		hint_1: "Sehr geschickter und wendiger Jäger.",
		hint_2: "Hat ein langes, schlankes Fell und bewegt sich lautlos.",
		hint_3: "Ist oft in der Nähe von Häusern unterwegs und bekannt für seine Neugier.",
		trivia: "Martens can climb trees to escape predators.",
		Paw: "Schlanke Pfote mit scharfen Krallen für das Klettern.",
	},
	{
		id: 10,
		name_german: "Maus",
		name: "Mouse",
		hint_1: "Bewegt sich flink und bleibt oft unbemerkt.",
		hint_2: "Findet Nahrung auch an unerwarteten Orten.",
		hint_3: "Hat einen langen Schwanz und große, runde Ohren.",
		trivia: "Mice can squeeze through holes as small as a dime.",
		Paw: "Kleine Pfote mit empfindlichen Zehen für das Klettern und Graben.",
	},
	{
		id: 11,
		name_german: "Otter",
		name: "Otter",
		hint_1: "Verbringt viel Zeit zwischen zwei Elementen.",
		hint_2: "Hat ein dichtes, wasserabweisendes Fell.",
		hint_3: "Bewegt sich geschickt im Wasser und ernährt sich von Fischen.",
		trivia: "Otters hold hands while sleeping to avoid drifting apart.",
		Paw: "Breite, mit Schwimmhäuten versehene Pfote für effiziente Bewegungen im Wasser.",
	},
	{
		id: 12,
		name_german: "Rebhuhn",
		name: "Partridge",
		hint_1: "Hält sich meist am Boden auf.",
		hint_2: "Fliegt nur bei Gefahr auf und legt kurze Strecken zurück.",
		hint_3: "Hat ein tarnfarbenes Federkleid und ein rundliches Erscheinungsbild.",
		trivia: "Partridges form monogamous pairs during the breeding season.",
		Paw: "Kleine, kräftige Pfote für schnelles Laufen auf festem Untergrund.",
	},
	{
		id: 13,
		name_german: "Reh",
		name: "Roe Deer",
		hint_1: "Lebt in Wäldern und auf Wiesen.",
		hint_2: "Hat große, aufmerksame Augen und ist sehr scheu.",
		hint_3: "Besitzt ein kleines, elegantes Geweih und ist oft in der Dämmerung aktiv.",
		trivia: "Roe deer can make a barking sound when alarmed.",
		Paw: "Schmale, gespreizte Hufabdrücke, typisch für Huftiere.",
	},
	{
		id: 14,
		name_german: "Reiher",
		name: "Heron",
		hint_1: "Verbringt viel Zeit in der Nähe von Gewässern.",
		hint_2: "Steht oft regungslos und wartet geduldig auf Beute.",
		hint_3: "Hat lange Beine und einen spitzen Schnabel für den Fischfang.",
		trivia: "Herons can hunt both day and night thanks to excellent eyesight.",
		Paw: "Lange, schmale Zehen für das Stehen auf weichem Untergrund.",
	},
	{
		id: 15,
		name_german: "Rothirsch",
		name: "Red Deer",
		hint_1: "Bewohnt Wälder und Lichtungen.",
		hint_2: "Die männlichen Tiere tragen eine beeindruckende Kopfbedeckung.",
		hint_3: "Sein markantes Röhren ist in der Brunftzeit weithin zu hören.",
		trivia: "Red deer antlers can grow up to 1 meter in length.",
		Paw: "Große, tief eingeschnittene Hufspuren mit parallelen Linien.",
	},
	{
		id: 16,
		name_german: "Waschbär",
		name: "Raccoon",
		hint_1: "Sehr geschickt und anpassungsfähig, oft in der Nähe von Siedlungen zu finden.",
		hint_2: "Besitzt geschickte Vorderpfoten, mit denen Nahrung ertastet wird.",
		hint_3: "Hat eine markante Gesichtsmaske und einen buschigen Schwanz mit Ringelmuster.",
		trivia: "Raccoons can remember solutions to tasks for years.",
		Paw: "Kleine, menschenähnliche Pfote mit fünf beweglichen Fingern.",
	},
	{
		id: 17,
		name_german: "Wildschwein",
		name: "Wild Boar",
		hint_1: "Durchwühlt oft den Boden auf der Suche nach Nahrung.",
		hint_2: "Besitzt kräftige Hauer, die als Waffe dienen.",
		hint_3: "Lebt in Gruppen, sogenannten Rotten, und ist sehr wehrhaft.",
		trivia: "Wild boars can run up to 40 km/h despite their heavy build.",
		Paw: "Große, gespreizte Hufspuren mit zwei sichtbaren Afterklauen.",
	},
	{
		id: 18,
		name_german: "Wolf",
		name: "Wolf",
		hint_1: "Durchstreift weite Gebiete auf der Suche nach Nahrung.",
		hint_2: "Lebt in enger Gemeinschaft mit Artgenossen.",
		hint_3: "Sein Heulen ist über weite Entfernungen zu hören.",
		trivia: "Wolves can communicate using over 10 different vocalizations.",
		Paw: "Große, kräftige Pfote mit markanten Krallen und sichtbaren Ballen.",
	},
];

export default data;
